# Generated by Django 3.1 on 2023-09-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'uf',
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codibge', models.IntegerField()),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='IBGE.uf')),
            ],
            options={
                'db_table': 'municipios',
            },
        ),
    ]
