# Generated by Django 3.1 on 2023-09-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codbanco', models.CharField(blank=True, max_length=3, null=True)),
                ('banco', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'bancos',
            },
        ),
        migrations.CreateModel(
            name='TipoConta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoconta', models.CharField(blank=True, max_length=3, null=True)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
                ('codbanco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='banco.bancos')),
            ],
            options={
                'db_table': 'tipoconta',
            },
        ),
    ]
