# Generated by Django 3.2 on 2023-10-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_entidade', '0002_usuarioentidade_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioentidade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
