# Generated by Django 3.1 on 2023-09-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SFP006',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdsecreta', models.CharField(blank=True, max_length=3, null=True)),
                ('cdsetor', models.CharField(blank=True, max_length=3, null=True)),
                ('cddepart', models.CharField(blank=True, max_length=3, null=True)),
                ('descricao', models.CharField(blank=True, max_length=40, null=True)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.entidade')),
            ],
            options={
                'verbose_name': 'sfp006',
                'verbose_name_plural': 'Lotacoes',
                'db_table': 'sfp006',
            },
        ),
    ]
