# Generated by Django 3.1 on 2023-09-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SFPD9924',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=3, null=True)),
                ('escola', models.CharField(blank=True, max_length=40, null=True)),
                ('obs', models.CharField(blank=True, max_length=40, null=True)),
                ('cdsecreta', models.CharField(blank=True, max_length=10, null=True)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.entidade')),
            ],
            options={
                'verbose_name': 'sfpdD9924',
                'verbose_name_plural': 'Unidade de Trabalho',
                'db_table': 'sfpd9924',
            },
        ),
    ]
