CH_SEXO = (('2', 'FEMININO'), ('1', 'MASCULINO'))

CH_TEMPO_RESIDENCIA = (('1', 'Prazo Inderteminado'), ('2','Prazo Determinado'))

CH_CONDICAO_ESTRANGEIRO = (('1', 'Refugiado'), ('2', 'Solicitante de Refúgio'),
                           ('3', 'Permanência no Brasil em razão de reunião familiar'),
                           ('4', 'Beneficiado pelo acordo entre países do Mercosul'),
                           ('5', 'Dependente de agente diplomático e/ou consular de países que mantêm acordo de reciprocidadepara o exercício de atividade remunerada no Brasil'),
                           ('6', 'Beneficiado pelo Tratado de Amizade, Cooperação e Consulta entre a República Federativa do Brasil e a República Portuguesa'),
                           ('7', 'Outra Condição'))

CH_GRAU_INSTRUCAO = (('1', 'Analfabeto, inclusive o que, embora tenha recebido instrução, não se alfabetizou.'),
                     ('2', 'Até o 5º ano incompleto do ensino fundamental.'),
                     ('3', '5º ano completo do ensino fundamental.'),
                     ('4', 'Do 6º ao 9º ano do ensino fundamental incompleto.'),
                     ('5', 'Ensino fundamental completo'),
                     ('6', 'Ensino médio incompleto.'),
                     ('7', 'Ensino médio completo.'),
                     ('8', 'Educação superior incompleta.'),
                     ('9', 'Educação superior completa.'),
                     ('A', 'Mestrado completo.'),
                     ('B', 'Doutorado completo.'),
                     ('C', 'Pós graduação completo'))

CH_ESTCIVIL = (('1', 'SOLTEIRO'),
               ('2', 'CASADO'),
               ('3', 'DIVORCIADO'),
               ('4', 'ESTÁVEL'),
               ('5', 'VIÚVO'),
               ('6', 'DESQUITADO E OUTROS'))

CH_SIM_NAO = (('S', 'SIM'), ('N', 'NÃO'))

CH_TRUE_FALSE = (('T', 'VERDADEIRO'), ('F', 'FALSO'))

CH_NACIONALIDADE = (('10', 'Brasileiro'),
                    ('20', 'Naturalizado Brasileiro'),
                    ('21', 'Argentino'),
                    ('22', 'Boliviano'),
                    ('23', 'Chileno'),
                    ('24', 'Paraguaio'),
                    ('25', 'Uruguaio'),
                    ('26', 'Venezuelano'),
                    ('27', 'Colombiano'),
                    ('28', 'Peruano'),
                    ('29', 'Equatoriano'),
                    ('30', 'Alemão'),
                    ('31', 'Belga'),
                    ('32', 'Britânico'),
                    ('34', 'Canadense'),
                    ('35', 'Espanhol'),
                    ('36', 'Norte-Americano (EUA)'),
                    ('37', 'Francês'),
                    ('38', 'Suíço'),
                    ('39', 'Italiano'),
                    ('40', 'Haitiano'),
                    ('41', 'Japonês'),
                    ('42', 'Chinês'),
                    ('43', 'Coreano'),
                    ('44', 'Russo'),
                    ('45', 'Português'),
                    ('46', 'Paquistanês'),
                    ('47', 'Indiano'),
                    ('48', 'Outros'),
                    ('49', 'Latino Americanos'),
                    ('50', 'Outros'),
                    ('51', 'Asiáticos'),
                    ('52', 'Bengalês'),
                    ('53', 'Outros'),
                    ('54', 'Europeus'),
                    ('55', 'Angolano'),
                    ('56', 'Congolês'),
                    ('57', 'Sul – Africano'),
                    ('58', 'Ganês'),
                    ('59', 'Senegalês'),
                    ('60', 'Outros'),
                    ('61', 'Africanos'),
                    ('62', 'Outros'))

CH_TIPO_LOGRADOURO = (('1', 'ACAMPAMENTO'),
                      ('2', 'ACESSO'),
                      ('3', 'ACESSO LOCAL'),
                      ('4', 'ADRO'),
                      ('5', 'AEROPORTO'),
                      ('6', 'ALAMEDA'),
                      ('7', 'ALTO'),
                      ('8', 'ANEL VIÁRIO'),
                      ('9', 'ANTIGA ESTAÇÃO'),
                      ('10', 'ANTIGA ESTRADA'),
                      ('11', 'ÁREA'),
                      ('12', 'ÁREA ESPECIAL'),
                      ('13', 'ÁREA VERDE'),
                      ('14', 'ARTÉRIA'),
                      ('15', 'ATALHO'),
                      ('16', 'AVENIDA'),
                      ('17', 'AVENIDA CONTORNO'),
                      ('18', 'AVENIDA MARGINAL'),
                      ('19', 'AVENIDA MARGINAL DIREITA'),
                      ('20', 'AVENIDA MARGINAL ESQUERDA'),
                      ('21', 'AVENIDA MARGINAL NORTE'),
                      ('22', 'AVENIDA PERIMETRAL'),
                      ('23', 'BAIXA'),
                      ('24', 'BALÃO'),
                      ('25', 'BECO'),
                      ('26', 'BELVEDERE'),
                      ('27', 'BLOCO'),
                      ('28', 'BLOCOS'),
                      ('29', 'BOSQUE'),
                      ('30', 'BOULEVARD'),
                      ('31', 'BULEVAR'),
                      ('32', 'BURACO'),
                      ('33', 'CAIS'),
                      ('34', 'CALÇADA'),
                      ('35', 'CALÇADÃO'),
                      ('36', 'CAMINHO'),
                      ('37', 'CAMINHO DE SERVIDÃO'),
                      ('38', 'CAMPO'),
                      ('39', 'CAMPUS'),
                      ('40', 'CANAL'),
                      ('41', 'CHÁCARA'),
                      ('42', 'CICLOVIA'),
                      ('43', 'CIRCULAR'),
                      ('44', 'COLÔNIA'),
                      ('45', 'COMPLEXO VIÁRIO'),
                      ('46', 'COMUNIDADE'),
                      ('47', 'CONDOMÍNIO'),
                      ('48', 'CONDOMÍNIO RESIDENCIAL'),
                      ('49', 'CONJUNTO'),
                      ('50', 'CONJUNTO HABITACIONAL'),
                      ('51', 'CONJUNTO MUTIRÃO'),
                      ('52', 'CONJUNTO RESIDENCIAL'),
                      ('53', 'CONTORNO'),
                      ('54', 'CORREDOR'),
                      ('55', 'CÓRREGO'),
                      ('56', 'DESCIDA'),
                      ('57', 'DESVIO'),
                      ('58', 'DISTRITO'),
                      ('59', 'EIXO'),
                      ('60', 'EIXO INDUSTRIAL'),
                      ('61', 'EIXO PRINCIPAL'),
                      ('62', 'ELEVADA'),
                      ('63', 'ENTRADA PARTICULAR'),
                      ('64', 'ENTRE QUADRA'),
                      ('65', 'ESCADA'),
                      ('66', 'ESCADA DE PEDRA'),
                      ('67', 'ESCADARIA'),
                      ('68', 'ESPLANADA'),
                      ('69', 'ESTAÇÃO'),
                      ('70', 'ESTACIONAMENTO'),
                      ('71', 'ESTÁDIO'),
                      ('72', 'ESTRADA'),
                      ('73', 'ESTRADA ANTIGA'),
                      ('74', 'ESTRADA DE FERRO'),
                      ('75', 'ESTRADA DE LIGAÇÃO'),
                      ('76', 'ESTRADA DE SERVIDÃO'),
                      ('77', 'ESTRADA ESTADUAL'),
                      ('78', 'ESTRADA INTERMUNICIPAL'),
                      ('79', 'ESTRADA MUNICIPAL'),
                      ('80', 'ESTRADA NOVA'),
                      ('81', 'ESTRADA PARTICULAR'),
                      ('82', 'ESTRADA VELHA'),
                      ('83', 'ESTRADA VICINAL'),
                      ('84', 'FAVELA'),
                      ('85', 'FAZENDA'),
                      ('86', 'FEIRA'),
                      ('87', 'FERROVIA'),
                      ('88', 'FONTE'),
                      ('89', 'FORTE'),
                      ('90', 'GALERIA'),
                      ('91', 'GLEBA'),
                      ('92', 'GRANJA'),
                      ('93', 'ILHA'),
                      ('94', 'JARDIM'),
                      ('95', 'JARDIM RESIDENCIAL'),
                      ('96', 'JARDINETE'),
                      ('97', 'LADEIRA'),
                      ('98', 'LAGO'),
                      ('99', 'LAGOA'),
                      ('100', 'LARGO'),
                      ('101', 'LOTEAMENTO'),
                      ('102', 'MARGEM'),
                      ('103', 'MARGINAL'),
                      ('104', 'MERCADO'),
                      ('105', 'MÓDULO'),
                      ('106', 'MONTE'),
                      ('107', 'MORRO'),
                      ('108', 'NOVA AVENIDA'),
                      ('109', 'NÚCLEO'),
                      ('110', 'NÚCLEO HABITACIONAL'),
                      ('111', 'NÚCLEO RURAL'),
                      ('112', 'OUTEIRO'),
                      ('113', 'PARADA'),
                      ('114', 'PARALELA'),
                      ('115', 'PARQUE'),
                      ('116', 'PARQUE MUNICIPAL'),
                      ('117', 'PARQUE RESIDENCIAL'),
                      ('118', 'PASSAGEM'),
                      ('119', 'PASSAGEM DE PEDESTRES'),
                      ('120', 'PASSAGEM SUBTERRÂNEA'),
                      ('121', 'PASSARELA'),
                      ('122', 'PASSEIO'),
                      ('123', 'PASSEIO PÚBLICO'),
                      ('124', 'PÁTIO'),
                      ('125', 'PONTA'),
                      ('126', 'PONTE'),
                      ('127', 'PORTO'),
                      ('128', 'POVOADO'),
                      ('129', 'PRAÇA'),
                      ('130', 'PRAÇA DE ESPORTES'),
                      ('131', 'PRAIA'),
                      ('132', 'PROLONGAMENTO'),
                      ('133', 'QUADRA'),
                      ('134', 'QUINTA'),
                      ('135', 'RAMAL'),
                      ('136', 'RAMPA'),
                      ('137', 'RECANTO'),
                      ('138', 'RESIDENCIAL'),
                      ('139', 'RETA'),
                      ('140', 'RETIRO'),
                      ('141', 'RETORNO'),
                      ('142', 'RODO ANEL'),
                      ('143', 'RODOVIA'),
                      ('144', 'ROTATÓRIA'),
                      ('145', 'RÓTULA'),
                      ('146', 'RUA'),
                      ('147', 'RUA DE LIGAÇÃO'),
                      ('148', 'RUA DE PEDESTRE'),
                      ('149', 'RUA PARTICULAR'),
                      ('150', 'RUA PRINCIPAL'),
                      ('151', 'RUA PROJETADA'),
                      ('152', 'RUA VELHA'),
                      ('153', 'RUA VICINAL'),
                      ('154', 'RUELA'),
                      ('155', 'SERVIDÃO'),
                      ('156', 'SERVIDÃO DE PASSAGEM'),
                      ('157', 'SETOR'),
                      ('158', 'SÍTIO'),
                      ('159', 'SUBIDA'),
                      ('160', 'TERCEIRA AVENIDA'),
                      ('161', 'TERMINAL'),
                      ('162', 'TRAVESSA'),
                      ('163', 'TRAVESSA PARTICULAR'),
                      ('164', 'TRECHO'),
                      ('165', 'TREVO'),
                      ('166', 'TRINCHEIRA'),
                      ('167', 'TÚNEL'),
                      ('168', 'UNIDADE'),
                      ('169', 'VALA'),
                      ('170', 'VALE'),
                      ('171', 'VARIANTE DA ESTRADA'),
                      ('172', 'VEREDA'),
                      ('173', 'VIA'),
                      ('174', 'VIA COLETORA'),
                      ('175', 'VIA COSTEIRA'),
                      ('176', 'VIA DE ACESSO'),
                      ('177', 'VIA DE PEDESTRES'),
                      ('178', 'VIA EXPRESSA'),
                      ('179', 'VIA LATERAL'),
                      ('180', 'VIA LITORANEA'),
                      ('181', 'VIA LOCAL'),
                      ('182', 'VIA MARGINAL'),
                      ('183', 'VIA PRINCIPAL'),
                      ('184', 'VIADUTO'),
                      ('185', 'VIELA'),
                      ('186', 'VILA'),
                      ('187', 'ZIGUE-ZAGUE'))

CH_ESFERA = (('1', 'FEDERAL'),
             ('2', 'ESTADUAL'),
             ('3', 'MUNICIPAL'))

CH_REGIME = (('1', 'ESTATUARIO'),
             ('2', 'CELETISTA'),
             ('3', 'OUTROS'))

CH_NIVEL_INSTRUCAO = (('1', 'LIVRE'),
                      ('2', 'PROFISSIONALIZANTE'),
                      ('3', 'TÉCNICO'),
                      ('4', 'SUPERIOR SEQUENCIAL'),
                      ('5', 'SUPERIOR TECNÓLOGO'),
                      ('6', 'SUPERIOR GRADUAÇÃO'),
                      ('7', 'PÓS GRAD. ESPECIALIZAÇÃO'),
                      ('8', 'PÓS GRAD. MESTRADO'),
                      ('9', 'DOUTORADO'),
                      ('10', 'PÓS DOUTORADO'))

CH_CODFOL = (('1', 'Afastamento'),
             ('2', 'Afastamento Aposnetadoria'),
             ('3', 'Aguardando Aposentadoria'),
             ('4', 'Auxílio Doença'),
             ('5', 'Disposição com Ônus'),
             ('6', 'Disposição sem Ônus'),
             ('7', 'Licença INSS'),
             ('8', 'Licença Maternidade'),
             ('9', 'Licença Medica'),
             ('10', 'Licença para Interesse Particular'),
             ('11', 'Licença para Tratamento de Saúde'),
             ('12', 'Licença Premio'),
             ('13', 'Licença sem Vencimento'),
             ('14', 'Licença Serviço Militar'),
             ('15', 'Demissão'),
             ('16', 'GESTOR'),
             ('17', 'Licença para Atividade Política'),
             ('18', 'Afastamento Preventivo - PAD'),
             ('19', 'Licença para Acompanhar Cônjuge'))

CH_RACA = (('1', 'Branco'),
           ('2', 'Preto'),
           ('3', 'Pardo'),
           ('4', 'Amarelo'),
           ('5', 'Indígena'))

CH_TIPO_SANGUINEO = (('1', 'A+'),
                     ('2', 'A-'),
                     ('3', 'B+'),
                     ('4', 'B-'),
                     ('5', 'AB+'),
                     ('6', 'AB-'),
                     ('7', 'O+'),
                     ('8', 'O-'))

CH_TIPO_DEF_FISICA = (('1', 'CID 10 - G82 Paraplegia e tetraplegia'),
                      ('2', 'CID 10 - G82.0 Paraplegia flácida'),
                      ('3', 'CID 10 - G82.1 Paraplegia espástica'),
                      ('4', 'CID 10 - G82.2 Paraplegia não especificada'),
                      ('5', 'CID 10 - G82.3 Tetraplegia flácida'),
                      ('6', 'CID 10 - G82.4 Tetraplegia espástica'),
                      ('7', 'CID 10 - G82.5 Tetraplegia não especificada'),
                      ('8', 'CID 10 - G83 Outras síndromes paralíticas'),
                      ('9', 'CID 10 - G83.0 Diplegia dos membros superiores'),
                      ('10', 'CID 10 - G83.1 Monoplegia do membro inferior'),
                      ('11', 'CID 10 - G83.2 Monoplegia do membro superior'),
                      ('12', 'CID 10 - G83.3 Monoplegia não especificada'),
                      ('13', 'CID 10 - G83.4 Síndrome da cauda eqüina'),
                      ('14', 'CID 10 - G83.8 Outras síndromes paralíticas especificadas'),
                      ('15', 'CID 10 - G83.9 Síndrome paralítica não especificada'),
                      ('16', 'CID 10 - G81 Hemiplegia'),
                      ('17', 'CID 10 - G81 Hemiplegia'),
                      ('18', 'CID 10 - G81.0 Hemiplegia flácida'),
                      ('19', 'CID 10 - G81.1 Hemiplegia espástica'),
                      ('20', 'CID 10 - G81.9 Hemiplegia não especificada'),
                      ('21', 'CID 10 - S88 Amputação traumática da perna'),
                      ('22', 'CID 10 - S88.0 Amputação traumática ao nível do joelho'),
                      ('23', 'CID 10 - S88.1 Amputação traumática entre o joelho e o tornozelo'),
                      ('24', 'CID 10 - S88.9 Amputação traumática da perna ao nível não especificado'),
                      ('25', 'CID 10 - G80 Paralisia cerebral'),
                      ('26', 'CID 10 - G80.0 Paralisia cerebral quadriplágica espástica'),
                      ('27', 'CID 10 - G80.1 Paralisia cerebral diplégica espástica'),
                      ('28', 'CID 10 - G80.2 Paralisia cerebral hemiplégica espástica'),
                      ('29', 'CID 10 - G80.3 Paralisia cerebral discinética'),
                      ('30', 'CID 10 - G80.4 Paralisia cerebral atáxica'),
                      ('31', 'CID 10 - G80.8 Outras formas de paralisia cerebral'),
                      ('32', 'CID 10 - G80.9 Paralisia cerebral não especificada'),
                      ('33', 'CID 10 - Z93 Orifícios artificiais'),
                      ('34', 'CID 10 - Z93.0 Traqueostomia'),
                      ('35', 'CID 10 - Z93.1 Gastrostomia'),
                      ('36', 'CID 10 - Z93.2 Ileostomia'),
                      ('37', 'CID 10 - Z93.3 Colostomia'),
                      ('38', 'CID 10 - Z93.4 Outros orifícios artificiais do trato gastrointestinal'),
                      ('39', 'CID 10 - Z93.5 Cistostomia'),
                      ('40', 'CID 10 - Z93.6 Outros orifícios artificiais do aparelho urinário'),
                      ('41', 'CID 10 - Z93.8 Outros orifícios artificiais'),
                      ('42', 'CID 10 - Z93.9 Orifício artificial não especificado'))

CH_TIPO_DEF_VISUAL = (('1', 'CID 10 - H53 Distúrbios visuais'),
                      ('2', 'CID 10 - H53.0 Ambliopia por anopsia'),
                      ('3', 'CID 10 - H53.1 Distúrbios visuais subjetivos'),
                      ('4', 'CID 10 - H53.2 Diplopia'),
                      ('5', 'CID 10 - H53.3 Outros transtornos da visão binocular'),
                      ('6', 'CID 10 - H53.4 Defeitos do campo visual'),
                      ('7', 'CID 10 - H53.5 Deficiências da visão cromática'),
                      ('8', 'CID 10 - H53.6 Cegueira noturna'),
                      ('9', 'CID 10 - H53.8 Outros distúrbios visuais'),
                      ('10', 'CID 10 - H53.9 Distúrbio visual não especificado'))

CH_TIPO_DEF_MENTAL = (('1', 'CID 10 - Q99.2 Cromossomo X frágil'),
                      ('2', 'CID 10 - Q90 Síndrome de Down'),
                      ('3', 'CID 10 - Q90.0 Trissomia 21, não-disjunção meiótica'),
                      ('4', 'CID 10 - Q90.1 Trissomia 21, mosaicismo (não-disjunção mitótica)'),
                      ('5', 'CID 10 - Q90.2 Trissomia 21, translocação'),
                      ('6', 'CID 10 - Q90.9 Síndrome de Down não especificada'),
                      ('7', 'CID 10 - R62 Retardo do desenvolvimento fisiológico normal'),
                      ('8', 'CID 10 - R62.0 Retardo de maturação'),
                      ('9', 'CID 10 - R62.8 Outras formas de retardo do desenvolvimento fisiológico normal'),
                      ('10', 'CID 10 - R62.9 Retardo do desenvolvimento fisiológico normal, não especificado'))

CH_CONSELHOS = (('CAU', 'CAU'),
                ('CFT', 'CFT'),
                ('CNV', 'CNV'),
                ('CONFEA', 'CONFEA'),
                ('COREN', 'COREN'),
                ('CRA', 'CRA'),
                ('CRB', 'CRB'),
                ('CRC', 'CRC'),
                ('CREA', 'CREA'),
                ('CREF', 'CREF'),
                ('CREFITO', 'CREFITO'),
                ('CREMEC', 'CREMEC'),
                ('CRESS', 'CRESS'),
                ('CRF', 'CRF'),
                ('CRM', 'CRM'),
                ('CRMV', 'CRMV'),
                ('CRN', 'CRN'),
                ('CRO', 'CRO'),
                ('CRP', 'CRP'),
                ('CRQ', 'CRQ'),
                ('CRSS', 'CRSS'),
                ('CRTR', 'CRTR'),
                ('OAB', 'OAB'))

CH_STATUS = (('I', 'Importado'),
             ('E', 'Editado'),
             ('U', 'P.Funcionário'),
             ('F', 'Finalizado'))

CH_PARENTESCO = (('F', 'FILHO'),
                 ('C', 'CÔNJUGE'),
                 ('A', 'AVOS'),
                 ('P', 'PAI'),
                 ('M', 'MÃE'),
                 ('I', 'FILHO INVÁLIDO'),
                 ('E', 'NÃO ESPECIFICADO'))

CH_TIPOS_DOCS = (('RG', 'Identidade'),
                 ('CNH', 'Carteira de Habilitação'),
                 ('CRES', 'Comprovante de Residência'),
                 ('CERT', 'Certidão'),
                 ('DIPL', 'Diploma'),
                 ('OUT', 'Outros Documentos'))