# Generated by Django 3.1 on 2023-09-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SFPDXX25',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=3, null=True)),
                ('cargo2', models.CharField(blank=True, max_length=40, null=True)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.entidade')),
            ],
            options={
                'verbose_name': 'sfpdXX25',
                'verbose_name_plural': 'Cargos 2',
                'db_table': 'sfpdXX25',
            },
        ),
        migrations.CreateModel(
            name='SFP005',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=3, null=True)),
                ('cargo', models.CharField(blank=True, max_length=40, null=True)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.entidade')),
            ],
            options={
                'verbose_name': 'SFP005',
                'verbose_name_plural': 'Cargos',
                'db_table': 'sfp005',
            },
        ),
    ]
