# Generated by Django 3.2 on 2023-10-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFP005', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfp005',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sfpdxx25',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
