# Generated by Django 3.1 on 2023-09-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFG_VINC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vinculo', models.CharField(blank=True, max_length=2, null=True)),
                ('nm_vinculo', models.CharField(blank=True, max_length=40, null=True)),
                ('tribunal', models.CharField(blank=True, max_length=5, null=True)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.entidade')),
            ],
            options={
                'verbose_name': 'CFG_VINC',
                'verbose_name_plural': 'Vinculo',
                'db_table': 'CFG_VINC',
            },
        ),
    ]
