# Generated by Django 3.2 on 2023-10-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFP001', '0002_auto_20231004_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sfp001',
            name='foto',
        ),
        migrations.AlterField(
            model_name='sfp001',
            name='matricula',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='sfp001',
            name='nome',
            field=models.CharField(blank=True, db_index=True, max_length=70, null=True),
        ),
    ]
