# Generated by Django 3.2 on 2023-10-05 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SFP001', '0003_auto_20231005_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.TextField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotos', to='SFP001.sfp001')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'db_table': 'sfp001_foto',
            },
        ),
    ]
