# Generated by Django 3.2 on 2023-10-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFP001', '0004_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfp001',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sfp001',
            name='status',
            field=models.CharField(blank=True, choices=[('I', 'Importado'), ('E', 'Editado'), ('U', 'P.Funcionário'), ('F', 'Finalizado')], max_length=1, null=True),
        ),
    ]
