# Generated by Django 3.2 on 2024-01-25 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_alter_entidade_id'),
        ('SFP001', '0005_auto_20231016_1426'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='sfp001',
            index_together={('entidade', 'matricula'), ('entidade', 'nome')},
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_created=True, null=True)),
                ('tipo', models.CharField(choices=[('RG', 'Identidade'), ('CNH', 'Carteira de Habilitação'), ('CRES', 'Comprovante de Residência'), ('CERT', 'Certidão'), ('DIPL', 'Diploma'), ('OUT', 'Outros Documentos')], max_length=5)),
                ('documento', models.TextField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='SFP001.sfp001')),
            ],
            options={
                'verbose_name': 'Documentos',
                'verbose_name_plural': 'Documentos',
                'db_table': 'sfp001_documentos',
            },
        ),
    ]
