# Generated by Django 3.2 on 2024-04-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFP001', '0006_auto_20240125_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfp001',
            name='obsfuncionais',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
