# Generated by Django 3.2 on 2024-05-07 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SFP001', '0007_alter_sfp001_obsfuncionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfp001',
            name='condingestrang',
            field=models.CharField(blank=True, choices=[('1', 'Refugiado'), ('2', 'Solicitante de Refúgio'), ('3', 'Permanência no Brasil em razão de reunião familiar'), ('4', 'Beneficiado pelo acordo entre países do Mercosul'), ('5', 'Dependente de agente diplomático e/ou consular de países que mantêm acordo de reciprocidadepara o exercício de atividade remunerada no Brasil'), ('6', 'Beneficiado pelo Tratado de Amizade, Cooperação e Consulta entre a República Federativa do Brasil e a República Portuguesa'), ('7', 'Outra Condição')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sfp001',
            name='rnenum',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='sfp001',
            name='tmpresidestrang',
            field=models.CharField(blank=True, choices=[('1', 'Prazo Inderteminado'), ('2', 'Prazo Determinado')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='SFP001.sfp001'),
        ),
        migrations.AlterField(
            model_name='sfp001',
            name='casadocombr',
            field=models.CharField(blank=True, choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sfp001',
            name='filhocombr',
            field=models.CharField(blank=True, choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sfp001',
            name='rneorgao',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
