# Generated by Django 3.1 on 2023-09-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_entidade', models.IntegerField(verbose_name='Código da entidades')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('razao', models.CharField(max_length=100)),
                ('fone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('fax', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=60)),
                ('log_numero', models.CharField(max_length=5, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=40, null=True)),
                ('bairro', models.CharField(max_length=40)),
                ('cidade', models.CharField(max_length=40)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('brasao', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('arqv_importacao', models.FileField(blank=True, null=True, upload_to='arqv_importacao/')),
                ('entidade_ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
    ]
