# Generated by Django 3.1 on 2023-09-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=60)),
                ('obrigatorio', models.BooleanField(default=False, null=True)),
                ('nao_importar', models.BooleanField(default=False, null=True)),
                ('nao_visualizar_serv', models.BooleanField(default=False, null=True)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.entidade')),
            ],
            options={
                'db_table': 'Controle',
            },
        ),
    ]
